/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShadowRouteImport } from './routes/shadow'
import { Route as ProphecyRouteImport } from './routes/prophecy'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicScrapyIngestRouteImport } from './routes/api/public/scrapy-ingest'
import { Route as ApiPublicRunRecipesRouteImport } from './routes/api/public/run-recipes'
import { Route as ApiPublicRunMonitoringRouteImport } from './routes/api/public/run-monitoring'
import { Route as ApiPublicRunBulkLookupsRouteImport } from './routes/api/public/run-bulk-lookups'
import { Route as ApiPublicRerunUnderwriteRouteImport } from './routes/api/public/rerun-underwrite'

const ShadowRoute = ShadowRouteImport.update({
  id: '/shadow',
  path: '/shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProphecyRoute = ProphecyRouteImport.update({
  id: '/prophecy',
  path: '/prophecy',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScrapyIngestRoute = ApiPublicScrapyIngestRouteImport.update({
  id: '/api/public/scrapy-ingest',
  path: '/api/public/scrapy-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunRecipesRoute = ApiPublicRunRecipesRouteImport.update({
  id: '/api/public/run-recipes',
  path: '/api/public/run-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunMonitoringRoute = ApiPublicRunMonitoringRouteImport.update({
  id: '/api/public/run-monitoring',
  path: '/api/public/run-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunBulkLookupsRoute = ApiPublicRunBulkLookupsRouteImport.update({
  id: '/api/public/run-bulk-lookups',
  path: '/api/public/run-bulk-lookups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRerunUnderwriteRoute =
  ApiPublicRerunUnderwriteRouteImport.update({
    id: '/api/public/rerun-underwrite',
    path: '/api/public/rerun-underwrite',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/admin': typeof AdminRoute
  '/deals': typeof DealsRoute
  '/monitoring': typeof MonitoringRoute
  '/prophecy': typeof ProphecyRoute
  '/shadow': typeof ShadowRoute
  '/api/public/rerun-underwrite': typeof ApiPublicRerunUnderwriteRoute
  '/api/public/run-bulk-lookups': typeof ApiPublicRunBulkLookupsRoute
  '/api/public/run-monitoring': typeof ApiPublicRunMonitoringRoute
  '/api/public/run-recipes': typeof ApiPublicRunRecipesRoute
  '/api/public/scrapy-ingest': typeof ApiPublicScrapyIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/admin': typeof AdminRoute
  '/deals': typeof DealsRoute
  '/monitoring': typeof MonitoringRoute
  '/prophecy': typeof ProphecyRoute
  '/shadow': typeof ShadowRoute
  '/api/public/rerun-underwrite': typeof ApiPublicRerunUnderwriteRoute
  '/api/public/run-bulk-lookups': typeof ApiPublicRunBulkLookupsRoute
  '/api/public/run-monitoring': typeof ApiPublicRunMonitoringRoute
  '/api/public/run-recipes': typeof ApiPublicRunRecipesRoute
  '/api/public/scrapy-ingest': typeof ApiPublicScrapyIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/admin': typeof AdminRoute
  '/deals': typeof DealsRoute
  '/monitoring': typeof MonitoringRoute
  '/prophecy': typeof ProphecyRoute
  '/shadow': typeof ShadowRoute
  '/api/public/rerun-underwrite': typeof ApiPublicRerunUnderwriteRoute
  '/api/public/run-bulk-lookups': typeof ApiPublicRunBulkLookupsRoute
  '/api/public/run-monitoring': typeof ApiPublicRunMonitoringRoute
  '/api/public/run-recipes': typeof ApiPublicRunRecipesRoute
  '/api/public/scrapy-ingest': typeof ApiPublicScrapyIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/admin'
    | '/deals'
    | '/monitoring'
    | '/prophecy'
    | '/shadow'
    | '/api/public/rerun-underwrite'
    | '/api/public/run-bulk-lookups'
    | '/api/public/run-monitoring'
    | '/api/public/run-recipes'
    | '/api/public/scrapy-ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/admin'
    | '/deals'
    | '/monitoring'
    | '/prophecy'
    | '/shadow'
    | '/api/public/rerun-underwrite'
    | '/api/public/run-bulk-lookups'
    | '/api/public/run-monitoring'
    | '/api/public/run-recipes'
    | '/api/public/scrapy-ingest'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/admin'
    | '/deals'
    | '/monitoring'
    | '/prophecy'
    | '/shadow'
    | '/api/public/rerun-underwrite'
    | '/api/public/run-bulk-lookups'
    | '/api/public/run-monitoring'
    | '/api/public/run-recipes'
    | '/api/public/scrapy-ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  AdminRoute: typeof AdminRoute
  DealsRoute: typeof DealsRoute
  MonitoringRoute: typeof MonitoringRoute
  ProphecyRoute: typeof ProphecyRoute
  ShadowRoute: typeof ShadowRoute
  ApiPublicRerunUnderwriteRoute: typeof ApiPublicRerunUnderwriteRoute
  ApiPublicRunBulkLookupsRoute: typeof ApiPublicRunBulkLookupsRoute
  ApiPublicRunMonitoringRoute: typeof ApiPublicRunMonitoringRoute
  ApiPublicRunRecipesRoute: typeof ApiPublicRunRecipesRoute
  ApiPublicScrapyIngestRoute: typeof ApiPublicScrapyIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shadow': {
      id: '/shadow'
      path: '/shadow'
      fullPath: '/shadow'
      preLoaderRoute: typeof ShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prophecy': {
      id: '/prophecy'
      path: '/prophecy'
      fullPath: '/prophecy'
      preLoaderRoute: typeof ProphecyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrapy-ingest': {
      id: '/api/public/scrapy-ingest'
      path: '/api/public/scrapy-ingest'
      fullPath: '/api/public/scrapy-ingest'
      preLoaderRoute: typeof ApiPublicScrapyIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-recipes': {
      id: '/api/public/run-recipes'
      path: '/api/public/run-recipes'
      fullPath: '/api/public/run-recipes'
      preLoaderRoute: typeof ApiPublicRunRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-monitoring': {
      id: '/api/public/run-monitoring'
      path: '/api/public/run-monitoring'
      fullPath: '/api/public/run-monitoring'
      preLoaderRoute: typeof ApiPublicRunMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-bulk-lookups': {
      id: '/api/public/run-bulk-lookups'
      path: '/api/public/run-bulk-lookups'
      fullPath: '/api/public/run-bulk-lookups'
      preLoaderRoute: typeof ApiPublicRunBulkLookupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rerun-underwrite': {
      id: '/api/public/rerun-underwrite'
      path: '/api/public/rerun-underwrite'
      fullPath: '/api/public/rerun-underwrite'
      preLoaderRoute: typeof ApiPublicRerunUnderwriteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  AdminRoute: AdminRoute,
  DealsRoute: DealsRoute,
  MonitoringRoute: MonitoringRoute,
  ProphecyRoute: ProphecyRoute,
  ShadowRoute: ShadowRoute,
  ApiPublicRerunUnderwriteRoute: ApiPublicRerunUnderwriteRoute,
  ApiPublicRunBulkLookupsRoute: ApiPublicRunBulkLookupsRoute,
  ApiPublicRunMonitoringRoute: ApiPublicRunMonitoringRoute,
  ApiPublicRunRecipesRoute: ApiPublicRunRecipesRoute,
  ApiPublicScrapyIngestRoute: ApiPublicScrapyIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
